"""Failure classes — representation vs experiment budget are not the same."""

CANDIDATE_REGISTRY_SATURATION = "CANDIDATE_REGISTRY_SATURATION"
HYPOTHESIS_REPRESENTATION_FAILURE = "HYPOTHESIS_REPRESENTATION_FAILURE"
LAZY_MATERIALIZATION_FAILURE = "LAZY_MATERIALIZATION_FAILURE"
DEFERRED_CANDIDATE_STARVATION = "DEFERRED_CANDIDATE_STARVATION"
FAMILY_CONTINUATION_FAILURE = "FAMILY_CONTINUATION_FAILURE"
CANDIDATE_DUPLICATION = "CANDIDATE_DUPLICATION"
NOVELTY_FARMING = "NOVELTY_FARMING"
EPISTEMIC_SCHEDULING_FAILURE = "EPISTEMIC_SCHEDULING_FAILURE"
EXPERIMENT_ALLOCATION_FAILURE = "EXPERIMENT_ALLOCATION_FAILURE"
HYPOTHESIS_DISCRIMINATION_FAILURE = "HYPOTHESIS_DISCRIMINATION_FAILURE"
CAUSAL_LOCALIZATION_FAILURE = "CAUSAL_LOCALIZATION_FAILURE"
FALSIFICATION_FAILURE = "FALSIFICATION_FAILURE"
REPRODUCTION_FAILURE = "REPRODUCTION_FAILURE"
VERIFICATION_FAILURE = "VERIFICATION_FAILURE"
EXPERIMENT_LANGUAGE_INSUFFICIENT = "EXPERIMENT_LANGUAGE_INSUFFICIENT"
MISSING_CAPABILITY_NOT_IDENTIFIED = "MISSING_CAPABILITY_NOT_IDENTIFIED"
PRIMITIVE_SYNTHESIS_NOT_ATTEMPTED = "PRIMITIVE_SYNTHESIS_NOT_ATTEMPTED"
PRIMITIVE_NOT_REPRESENTABLE = "PRIMITIVE_NOT_REPRESENTABLE"
PRIMITIVE_VALIDATION_FAILURE = "PRIMITIVE_VALIDATION_FAILURE"
PRIMITIVE_EXECUTION_FAILURE = "PRIMITIVE_EXECUTION_FAILURE"
PRIMITIVE_NONINFORMATIVE = "PRIMITIVE_NONINFORMATIVE"
LANGUAGE_EXTENSION_FAILURE = "LANGUAGE_EXTENSION_FAILURE"
SYNTHESIS_ALLOCATION_FAILURE = "SYNTHESIS_ALLOCATION_FAILURE"
SYNTHESIS_CAPACITY_FAILURE = "SYNTHESIS_CAPACITY_FAILURE"
DUPLICATE_PRIMITIVE = "DUPLICATE_PRIMITIVE"
UNKNOWN_UNKNOWN_SYNTHESIS_FAILURE = "UNKNOWN_UNKNOWN_SYNTHESIS_FAILURE"
INSUFFICIENT_BUDGET = "INSUFFICIENT_BUDGET"
MODEL_RUNTIME_FAILURE = "MODEL_RUNTIME_FAILURE"
NO_ANOMALY = "NO_ANOMALY"
ANOMALY_BUT_NO_CAUSAL_LINK = "ANOMALY_BUT_NO_CAUSAL_LINK"
KNOWN_LANGUAGE_INSUFFICIENT = "KNOWN_LANGUAGE_INSUFFICIENT"
NEW_PROGRAM_NOT_FOUND = "NEW_PROGRAM_NOT_FOUND"
NEW_PRIMITIVE_NOT_FOUND = "NEW_PRIMITIVE_NOT_FOUND"
LANGUAGE_EXTENSION_HYPOTHESIS_FAILED = "LANGUAGE_EXTENSION_HYPOTHESIS_FAILED"
SUBSTRATE_SYNTHESIS_FAILED = "SUBSTRATE_SYNTHESIS_FAILED"
SUBSTRATE_VALIDATION_FAILED = "SUBSTRATE_VALIDATION_FAILED"
SEMANTIC_DUPLICATE = "SEMANTIC_DUPLICATE"
COMPUTATIONAL_CAPABILITY_NOT_REPRESENTABLE = "COMPUTATIONAL_CAPABILITY_NOT_REPRESENTABLE"
INVENTORY_CAPACITY_FAILURE = "INVENTORY_CAPACITY_FAILURE"
LEASE_FAILURE = "LEASE_FAILURE"
EXECUTION_FAILURE = "EXECUTION_FAILURE"
UNRESOLVED = "UNRESOLVED"
UNRESOLVED_INVISIBLE = "UNRESOLVED_INVISIBLE"


FAILURES = (
    CANDIDATE_REGISTRY_SATURATION,
    HYPOTHESIS_REPRESENTATION_FAILURE,
    LAZY_MATERIALIZATION_FAILURE,
    DEFERRED_CANDIDATE_STARVATION,
    FAMILY_CONTINUATION_FAILURE,
    CANDIDATE_DUPLICATION,
    NOVELTY_FARMING,
    EPISTEMIC_SCHEDULING_FAILURE,
    EXPERIMENT_ALLOCATION_FAILURE,
    HYPOTHESIS_DISCRIMINATION_FAILURE,
    CAUSAL_LOCALIZATION_FAILURE,
    FALSIFICATION_FAILURE,
    REPRODUCTION_FAILURE,
    VERIFICATION_FAILURE,
    INSUFFICIENT_BUDGET,
    MODEL_RUNTIME_FAILURE,
    EXPERIMENT_LANGUAGE_INSUFFICIENT,
    MISSING_CAPABILITY_NOT_IDENTIFIED,
    PRIMITIVE_SYNTHESIS_NOT_ATTEMPTED,
    PRIMITIVE_NOT_REPRESENTABLE,
    PRIMITIVE_VALIDATION_FAILURE,
    PRIMITIVE_EXECUTION_FAILURE,
    PRIMITIVE_NONINFORMATIVE,
    LANGUAGE_EXTENSION_FAILURE,
    SYNTHESIS_ALLOCATION_FAILURE,
    SYNTHESIS_CAPACITY_FAILURE,
    DUPLICATE_PRIMITIVE,
    UNKNOWN_UNKNOWN_SYNTHESIS_FAILURE,
    NO_ANOMALY,
    ANOMALY_BUT_NO_CAUSAL_LINK,
    KNOWN_LANGUAGE_INSUFFICIENT,
    NEW_PROGRAM_NOT_FOUND,
    NEW_PRIMITIVE_NOT_FOUND,
    LANGUAGE_EXTENSION_HYPOTHESIS_FAILED,
    SUBSTRATE_SYNTHESIS_FAILED,
    SUBSTRATE_VALIDATION_FAILED,
    SEMANTIC_DUPLICATE,
    COMPUTATIONAL_CAPABILITY_NOT_REPRESENTABLE,
    INVENTORY_CAPACITY_FAILURE,
    LEASE_FAILURE,
    EXECUTION_FAILURE,
    UNRESOLVED,
    UNRESOLVED_INVISIBLE,
)

__all__ = ["FAILURES"]
