"""Failure classes — representation vs experiment budget are not the same."""

CANDIDATE_REGISTRY_SATURATION = "CANDIDATE_REGISTRY_SATURATION"
HYPOTHESIS_REPRESENTATION_FAILURE = "HYPOTHESIS_REPRESENTATION_FAILURE"
LAZY_MATERIALIZATION_FAILURE = "LAZY_MATERIALIZATION_FAILURE"
DEFERRED_CANDIDATE_STARVATION = "DEFERRED_CANDIDATE_STARVATION"
FAMILY_CONTINUATION_FAILURE = "FAMILY_CONTINUATION_FAILURE"
CANDIDATE_DUPLICATION = "CANDIDATE_DUPLICATION"
NOVELTY_FARMING = "NOVELTY_FARMING"
EPISTEMIC_SCHEDULING_FAILURE = "EPISTEMIC_SCHEDULING_FAILURE"
EXPERIMENT_ALLOCATION_FAILURE = "EXPERIMENT_ALLOCATION_FAILURE"
HYPOTHESIS_DISCRIMINATION_FAILURE = "HYPOTHESIS_DISCRIMINATION_FAILURE"
CAUSAL_LOCALIZATION_FAILURE = "CAUSAL_LOCALIZATION_FAILURE"
FALSIFICATION_FAILURE = "FALSIFICATION_FAILURE"
REPRODUCTION_FAILURE = "REPRODUCTION_FAILURE"
VERIFICATION_FAILURE = "VERIFICATION_FAILURE"
INSUFFICIENT_BUDGET = "INSUFFICIENT_BUDGET"
MODEL_RUNTIME_FAILURE = "MODEL_RUNTIME_FAILURE"

FAILURES = (
    CANDIDATE_REGISTRY_SATURATION,
    HYPOTHESIS_REPRESENTATION_FAILURE,
    LAZY_MATERIALIZATION_FAILURE,
    DEFERRED_CANDIDATE_STARVATION,
    FAMILY_CONTINUATION_FAILURE,
    CANDIDATE_DUPLICATION,
    NOVELTY_FARMING,
    EPISTEMIC_SCHEDULING_FAILURE,
    EXPERIMENT_ALLOCATION_FAILURE,
    HYPOTHESIS_DISCRIMINATION_FAILURE,
    CAUSAL_LOCALIZATION_FAILURE,
    FALSIFICATION_FAILURE,
    REPRODUCTION_FAILURE,
    VERIFICATION_FAILURE,
    INSUFFICIENT_BUDGET,
    MODEL_RUNTIME_FAILURE,
)

__all__ = ["FAILURES"]
